#!/usr/bin/env bash
# Repeatable M1 acceptance harness (local-first).
# Automates must-pass M1-1…M1-5 from docs/acceptance-m1.md by driving
# ./run-openresty-demo.sh (OpenResty 1.19.3.2 baseline).
#
# Usage:
#   OPENRESTY_PREFIX=/usr/local/openresty ./scripts/accept-m1.sh
#
# Env (same as run-openresty-demo.sh):
#   OPENRESTY_PREFIX  LOADER_PORTS  TARGET  PIN_DIR  WAIT
#
# CI note: full accept needs self-hosted Linux ≥5.9 with sk_lookup, root/CAP_BPF,
# curl, and OpenResty 1.19.3.2 — not suitable for default GitHub-hosted runners.
# Prefer local / self-hosted; no workflow shipped by default.
#
# Writes machine summary to docs/acceptance-m1-last.json (generated; do not hand-edit).
# Exit non-zero if any of M1-1…M1-5 fails.
set -u
set -o pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

export CGO_ENABLED=0
OPENRESTY_PREFIX="${OPENRESTY_PREFIX:-}"
LOADER_PORTS="${LOADER_PORTS:-18081,18082,65500}"
TARGET="${TARGET:-127.0.0.1:8080}"
PIN_DIR="${PIN_DIR:-/sys/fs/bpf/waf-sklookup}"
WAIT="${WAIT:-60s}"
UNOPENED_PORT="${UNOPENED_PORT:-18083}"
SUMMARY_JSON="${SUMMARY_JSON:-$ROOT/docs/acceptance-m1-last.json}"
RUN_DEMO="./run-openresty-demo.sh"

export OPENRESTY_PREFIX LOADER_PORTS TARGET PIN_DIR WAIT CGO_ENABLED

HOST="${TARGET%%:*}"
INTERNAL_PORT="${TARGET##*:}"
if [[ "$HOST" == "$INTERNAL_PORT" ]]; then
  HOST="127.0.0.1"
  INTERNAL_PORT="8080"
fi

# Parse steered ports
PORTS=()
IFS=',' read -ra _raw_ports <<< "$LOADER_PORTS"
for p in "${_raw_ports[@]}"; do
  p="${p// /}"
  [[ -n "$p" ]] && PORTS+=("$p")
done
FIRST_PORT="${PORTS[0]:-18081}"
NEIGHBOR_PORT="${PORTS[1]:-18082}"

STARTED=0
CLEANED=0
OVERALL=0
TS_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
TS_CST="$(TZ=Asia/Shanghai date +%Y-%m-%dT%H:%M:%S%z)"

declare -A RESULT_STATUS
declare -A RESULT_DETAIL
for k in M1-1 M1-2 M1-3 M1-4 M1-5; do
  RESULT_STATUS[$k]="PENDING"
  RESULT_DETAIL[$k]=""
done
OPTIONAL_UNOPENED="SKIP"
OPTIONAL_DETAIL=""

log() { printf '%s\n' "$*"; }
err() { printf '%s\n' "$*" >&2; }

set_result() {
  local key="$1" status="$2" detail="$3"
  RESULT_STATUS[$key]="$status"
  RESULT_DETAIL[$key]="$detail"
  if [[ "$status" == "FAIL" ]]; then
    OVERALL=1
  fi
}

cleanup() {
  if [[ "$CLEANED" -eq 1 ]]; then
    return
  fi
  CLEANED=1
  if [[ "$STARTED" -eq 1 ]]; then
    log "=== cleanup: stop ==="
    "$RUN_DEMO" stop >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

find_openresty_bin() {
  if [[ -n "$OPENRESTY_PREFIX" && -x "$OPENRESTY_PREFIX/bin/openresty" ]]; then
    echo "$OPENRESTY_PREFIX/bin/openresty"
    return 0
  fi
  if command -v openresty >/dev/null 2>&1; then
    command -v openresty
    return 0
  fi
  return 1
}

json_escape() {
  python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()[:-1] if False else sys.argv[1]))' "$1"
}

write_summary() {
  local overall_s="FAIL"
  [[ "$OVERALL" -eq 0 ]] && overall_s="PASS"
  mkdir -p "$(dirname "$SUMMARY_JSON")"
  python3 - "$SUMMARY_JSON" <<'PY'
import json, os, sys
path = sys.argv[1]
# parent exports via env
data = {
  "note": "generated by scripts/accept-m1.sh — do not hand-edit; historical PASS evidence lives in docs/acceptance-m1.md",
  "generated_at_utc": os.environ.get("ACCEPT_TS_UTC", ""),
  "generated_at_asia_shanghai": os.environ.get("ACCEPT_TS_CST", ""),
  "overall": os.environ.get("ACCEPT_OVERALL", "FAIL"),
  "openresty_baseline": "1.19.3.2",
  "openresty_version": os.environ.get("ACCEPT_OR_VER", ""),
  "kernel": os.environ.get("ACCEPT_KERNEL", ""),
  "env": {
    "OPENRESTY_PREFIX": os.environ.get("OPENRESTY_PREFIX", ""),
    "LOADER_PORTS": os.environ.get("LOADER_PORTS", ""),
    "TARGET": os.environ.get("TARGET", ""),
    "PIN_DIR": os.environ.get("PIN_DIR", ""),
    "UNOPENED_PORT": os.environ.get("UNOPENED_PORT", ""),
  },
  "results": {
    "M1-1": {"status": os.environ["ACCEPT_M1_1"], "detail": os.environ.get("ACCEPT_M1_1_D", "")},
    "M1-2": {"status": os.environ["ACCEPT_M1_2"], "detail": os.environ.get("ACCEPT_M1_2_D", "")},
    "M1-3": {"status": os.environ["ACCEPT_M1_3"], "detail": os.environ.get("ACCEPT_M1_3_D", "")},
    "M1-4": {"status": os.environ["ACCEPT_M1_4"], "detail": os.environ.get("ACCEPT_M1_4_D", "")},
    "M1-5": {"status": os.environ["ACCEPT_M1_5"], "detail": os.environ.get("ACCEPT_M1_5_D", "")},
  },
  "optional": {
    "M1-9_unopened_port": {
      "status": os.environ.get("ACCEPT_OPT_UNOPENED", "SKIP"),
      "detail": os.environ.get("ACCEPT_OPT_UNOPENED_D", ""),
    }
  },
}
with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write("\n")
print(path)
PY
}

# ---------- 1) Preflight ----------
log "=== M1 accept: preflight ==="
KERNEL="$(uname -r)"
log "uname -r: $KERNEL"
log "uname -s: $(uname -s)"

OR_BIN=""
OR_VER=""
if OR_BIN="$(find_openresty_bin)"; then
  OR_VER="$("$OR_BIN" -v 2>&1 || true)"
  log "openresty: $OR_BIN ($OR_VER)"
else
  err "FAIL preflight: OpenResty not found (set OPENRESTY_PREFIX or put openresty in PATH)"
  set_result "M1-5" "FAIL" "openresty binary missing"
  # Still try to record summary and exit
  export ACCEPT_TS_UTC="$TS_UTC" ACCEPT_TS_CST="$TS_CST" ACCEPT_OVERALL="FAIL"
  export ACCEPT_OR_VER="" ACCEPT_KERNEL="$KERNEL"
  export ACCEPT_M1_1="FAIL" ACCEPT_M1_1_D="preflight aborted"
  export ACCEPT_M1_2="FAIL" ACCEPT_M1_2_D="preflight aborted"
  export ACCEPT_M1_3="FAIL" ACCEPT_M1_3_D="preflight aborted"
  export ACCEPT_M1_4="FAIL" ACCEPT_M1_4_D="preflight aborted"
  export ACCEPT_M1_5="FAIL" ACCEPT_M1_5_D="openresty binary missing"
  export ACCEPT_OPT_UNOPENED="SKIP" ACCEPT_OPT_UNOPENED_D="preflight aborted"
  write_summary || true
  exit 1
fi

if ! command -v curl >/dev/null 2>&1; then
  err "FAIL preflight: curl not in PATH"
  exit 1
fi
log "curl: $(command -v curl)"

if ! command -v sudo >/dev/null 2>&1; then
  err "FAIL preflight: sudo not in PATH (needed for loader / bpftool)"
  exit 1
fi

SK_OK=0
if command -v bpftool >/dev/null 2>&1; then
  if sudo bpftool feature list_builtins prog_types 2>/dev/null | grep -q sk_lookup; then
    SK_OK=1
    log "bpftool: sk_lookup available"
  else
    err "WARN: bpftool present but sk_lookup not listed in prog_types (continuing; loader may still fail)"
  fi
else
  err "WARN: bpftool not in PATH; cannot preflight sk_lookup (continuing)"
fi

if [[ ! -x "$RUN_DEMO" ]]; then
  chmod +x "$RUN_DEMO" || true
fi

# ---------- 2) Build + start ----------
log "=== M1 accept: start (build + OpenResty + loader) ==="
set +e
"$RUN_DEMO" stop >/dev/null 2>&1
set -e
if ! "$RUN_DEMO" start; then
  err "FAIL: run-openresty-demo.sh start"
  set_result "M1-1" "FAIL" "start failed"
  set_result "M1-2" "FAIL" "start failed"
  set_result "M1-3" "FAIL" "start failed"
  set_result "M1-4" "FAIL" "start failed"
  if [[ "$OR_VER" == *"1.19.3.2"* ]]; then
    set_result "M1-5" "PASS" "$OR_VER"
  else
    set_result "M1-5" "FAIL" "version string missing 1.19.3.2: $OR_VER"
  fi
  STARTED=1
  export ACCEPT_TS_UTC="$TS_UTC" ACCEPT_TS_CST="$TS_CST"
  export ACCEPT_OVERALL="FAIL" ACCEPT_OR_VER="$OR_VER" ACCEPT_KERNEL="$KERNEL"
  export ACCEPT_M1_1="${RESULT_STATUS[M1-1]}" ACCEPT_M1_1_D="${RESULT_DETAIL[M1-1]}"
  export ACCEPT_M1_2="${RESULT_STATUS[M1-2]}" ACCEPT_M1_2_D="${RESULT_DETAIL[M1-2]}"
  export ACCEPT_M1_3="${RESULT_STATUS[M1-3]}" ACCEPT_M1_3_D="${RESULT_DETAIL[M1-3]}"
  export ACCEPT_M1_4="${RESULT_STATUS[M1-4]}" ACCEPT_M1_4_D="${RESULT_DETAIL[M1-4]}"
  export ACCEPT_M1_5="${RESULT_STATUS[M1-5]}" ACCEPT_M1_5_D="${RESULT_DETAIL[M1-5]}"
  export ACCEPT_OPT_UNOPENED="SKIP" ACCEPT_OPT_UNOPENED_D="start failed"
  write_summary || true
  log "=== PASS/FAIL summary ==="
  for k in M1-1 M1-2 M1-3 M1-4 M1-5; do
    log "$k: ${RESULT_STATUS[$k]} — ${RESULT_DETAIL[$k]}"
  done
  log "OVERALL: FAIL"
  exit 1
fi
STARTED=1
set +e

TMPDIR_ACCEPT="$(mktemp -d)"
HDR="$TMPDIR_ACCEPT/hdr"
BODY="$TMPDIR_ACCEPT/body"

# ---------- 3) M1-5 version ----------
log "=== M1-5 OpenResty version ==="
if [[ "$OR_VER" == *"1.19.3.2"* ]]; then
  set_result "M1-5" "PASS" "$OR_VER"
  log "PASS M1-5: $OR_VER"
else
  set_result "M1-5" "FAIL" "expected 1.19.3.2 in version string; got: $OR_VER"
  err "FAIL M1-5: $OR_VER"
fi

# ---------- M1-1 bind check ----------
log "=== M1-1 bind check (internal only) ==="
BIND_OK=1
BIND_DETAIL=""
if command -v ss >/dev/null 2>&1; then
  SS_OUT="$(ss -lntp 2>/dev/null | grep -E ":(${INTERNAL_PORT}|${FIRST_PORT}|${NEIGHBOR_PORT}|65500)\\b" || true)"
  log "$SS_OUT"
  if echo "$SS_OUT" | grep -Eq ":(${FIRST_PORT}|${NEIGHBOR_PORT}|65500)\\b"; then
    # userspace LISTEN on steered ports is FAIL; ss may still show nothing useful — also check /proc
    :
  fi
fi
# /proc/net/tcp: state 0A = LISTEN; steered ports must not appear
PROC_LISTEN="$(python3 - "$FIRST_PORT" "$NEIGHBOR_PORT" <<'PY'
import sys
from pathlib import Path
steered = {int(x) for x in sys.argv[1:] if x.isdigit()}
steered |= {65500}
hits = []
for line in Path("/proc/net/tcp").read_text().splitlines()[1:]:
    f = line.split()
    if len(f) < 4 or f[3] != "0A":
        continue
    port = int(f[1].split(":")[1], 16)
    if port in steered:
        hits.append(str(port))
print(",".join(hits))
PY
)"
if [[ -n "$PROC_LISTEN" ]]; then
  BIND_OK=0
  BIND_DETAIL="userspace LISTEN on steered ports: $PROC_LISTEN"
else
  BIND_DETAIL="no userspace LISTEN on steered ports; internal TARGET=$TARGET"
fi
# Internal listen should exist
if ! python3 - "$INTERNAL_PORT" <<'PY'
import sys
from pathlib import Path
want = int(sys.argv[1])
for line in Path("/proc/net/tcp").read_text().splitlines()[1:]:
    f = line.split()
    if len(f) < 4 or f[3] != "0A":
        continue
    port = int(f[1].split(":")[1], 16)
    if port == want:
        sys.exit(0)
sys.exit(1)
PY
then
  BIND_OK=0
  BIND_DETAIL="internal listen :${INTERNAL_PORT} not found; $BIND_DETAIL"
fi
if [[ "$BIND_OK" -eq 1 ]]; then
  set_result "M1-1" "PASS" "$BIND_DETAIL"
  log "PASS M1-1: $BIND_DETAIL"
else
  set_result "M1-1" "FAIL" "$BIND_DETAIL"
  err "FAIL M1-1: $BIND_DETAIL"
fi

# ---------- M1-2 / M1-3 curl steered ports ----------
log "=== M1-2 / M1-3 curl steered ports ==="
M12_OK=1
M13_OK=1
M12_D=""
M13_D=""
SEEN_PORTS=()
for p in "${PORTS[@]}"; do
  log "--- curl http://${HOST}:${p}/ ---"
  if ! curl -sS -D "$HDR" -o "$BODY" --max-time 5 "http://${HOST}:${p}/"; then
    M12_OK=0
    M12_D="${M12_D}curl :${p} failed; "
    continue
  fi
  if grep -q "sk_lookup demo OK" "$BODY"; then
    M12_OK=0
    M12_D="${M12_D}:${p} hit toy HTTP; "
  fi
  if ! grep -q "OpenResty M1 OK" "$BODY"; then
    M12_OK=0
    M12_D="${M12_D}:${p} missing OpenResty M1 OK; "
  fi
  if ! grep -qi "Server: openresty" "$HDR"; then
    M12_OK=0
    M12_D="${M12_D}:${p} Server header not openresty; "
  else
    # reinforce M1-5 from Server header if present
    if grep -qi "Server: openresty/1.19.3.2" "$HDR"; then
      if [[ "${RESULT_STATUS[M1-5]}" != "PASS" ]]; then
        set_result "M1-5" "PASS" "Server: openresty/1.19.3.2 (from :${p})"
      fi
    fi
  fi
  if ! grep -qi "X-Waf-External-Port: ${p}" "$HDR"; then
    M13_OK=0
    M13_D="${M13_D}:${p} bad/missing X-Waf-External-Port; "
  fi
  if ! grep -q "waf_external_port=${p}" "$BODY"; then
    M13_OK=0
    M13_D="${M13_D}:${p} body waf_external_port != ${p}; "
  fi
  if grep -q "waf_external_port=${INTERNAL_PORT}" "$BODY" && [[ "$p" != "$INTERNAL_PORT" ]]; then
    M13_OK=0
    M13_D="${M13_D}:${p} reported internal port ${INTERNAL_PORT}; "
  fi
  SEEN_PORTS+=("$p")
done
if [[ "$M12_OK" -eq 1 ]]; then
  set_result "M1-2" "PASS" "OpenResty body+Server on ports ${LOADER_PORTS}"
  log "PASS M1-2"
else
  set_result "M1-2" "FAIL" "$M12_D"
  err "FAIL M1-2: $M12_D"
fi
if [[ "$M13_OK" -eq 1 && ${#SEEN_PORTS[@]} -ge 2 ]]; then
  set_result "M1-3" "PASS" "distinct X-Waf-External-Port / waf_external_port on ${LOADER_PORTS}"
  log "PASS M1-3"
elif [[ "$M13_OK" -eq 1 ]]; then
  set_result "M1-3" "FAIL" "need ≥2 steered ports to prove distinct external ports; got ${#SEEN_PORTS[@]}"
  err "FAIL M1-3: insufficient ports"
else
  set_result "M1-3" "FAIL" "$M13_D"
  err "FAIL M1-3: $M13_D"
fi

# ---------- 5) optional unopened port (before close so map still full) ----------
log "=== optional: unopened port :${UNOPENED_PORT} ==="
# skip if UNOPENED_PORT is in LOADER_PORTS
SKIP_UNOPENED=0
for p in "${PORTS[@]}"; do
  if [[ "$p" == "$UNOPENED_PORT" ]]; then
    SKIP_UNOPENED=1
  fi
done
if [[ "$SKIP_UNOPENED" -eq 1 ]]; then
  OPTIONAL_UNOPENED="SKIP"
  OPTIONAL_DETAIL="UNOPENED_PORT=${UNOPENED_PORT} is in LOADER_PORTS"
  log "SKIP optional unopened (port is steered)"
else
  if curl -sS --max-time 3 "http://${HOST}:${UNOPENED_PORT}/" -o /dev/null 2>/dev/null; then
    OPTIONAL_UNOPENED="FAIL"
    OPTIONAL_DETAIL="unopened :${UNOPENED_PORT} unexpectedly connected"
    err "FAIL optional M1-9: $OPTIONAL_DETAIL"
  else
    OPTIONAL_UNOPENED="PASS"
    OPTIONAL_DETAIL="unopened :${UNOPENED_PORT} connect failed (expected)"
    log "PASS optional: $OPTIONAL_DETAIL"
  fi
fi

# ---------- 4) M1-4 close-port ----------
log "=== M1-4 close-port ${FIRST_PORT} (neighbor ${NEIGHBOR_PORT}) ==="
M14_OK=1
M14_D=""
if ! "$RUN_DEMO" close-port "$FIRST_PORT"; then
  M14_OK=0
  M14_D="close-port ${FIRST_PORT} command failed; "
else
  sleep 0.5
  if curl -sS --max-time 3 "http://${HOST}:${FIRST_PORT}/" -o /dev/null 2>/dev/null; then
    M14_OK=0
    M14_D=":${FIRST_PORT} still reachable after close-port; "
  else
    M14_D=":${FIRST_PORT} connect fail after close; "
  fi
  if ! curl -sS -D "$HDR" -o "$BODY" --max-time 5 "http://${HOST}:${NEIGHBOR_PORT}/"; then
    M14_OK=0
    M14_D="${M14_D}neighbor :${NEIGHBOR_PORT} curl failed; "
  else
    if ! grep -q "OpenResty M1 OK" "$BODY"; then
      M14_OK=0
      M14_D="${M14_D}neighbor body not OpenResty; "
    else
      M14_D="${M14_D}neighbor :${NEIGHBOR_PORT} still 200/OpenResty; "
    fi
  fi
fi
if [[ "$M14_OK" -eq 1 ]]; then
  set_result "M1-4" "PASS" "$M14_D"
  log "PASS M1-4: $M14_D"
else
  set_result "M1-4" "FAIL" "$M14_D"
  err "FAIL M1-4: $M14_D"
fi

# ---------- summary ----------
if [[ "$OVERALL" -eq 0 ]]; then
  OVERALL_S="PASS"
else
  OVERALL_S="FAIL"
fi

export ACCEPT_TS_UTC="$TS_UTC" ACCEPT_TS_CST="$TS_CST"
export ACCEPT_OVERALL="$OVERALL_S" ACCEPT_OR_VER="$OR_VER" ACCEPT_KERNEL="$KERNEL"
export ACCEPT_M1_1="${RESULT_STATUS[M1-1]}" ACCEPT_M1_1_D="${RESULT_DETAIL[M1-1]}"
export ACCEPT_M1_2="${RESULT_STATUS[M1-2]}" ACCEPT_M1_2_D="${RESULT_DETAIL[M1-2]}"
export ACCEPT_M1_3="${RESULT_STATUS[M1-3]}" ACCEPT_M1_3_D="${RESULT_DETAIL[M1-3]}"
export ACCEPT_M1_4="${RESULT_STATUS[M1-4]}" ACCEPT_M1_4_D="${RESULT_DETAIL[M1-4]}"
export ACCEPT_M1_5="${RESULT_STATUS[M1-5]}" ACCEPT_M1_5_D="${RESULT_DETAIL[M1-5]}"
export ACCEPT_OPT_UNOPENED="$OPTIONAL_UNOPENED" ACCEPT_OPT_UNOPENED_D="$OPTIONAL_DETAIL"
export UNOPENED_PORT

SUMMARY_PATH="$(write_summary)"
log "=== PASS/FAIL summary ==="
for k in M1-1 M1-2 M1-3 M1-4 M1-5; do
  log "$k: ${RESULT_STATUS[$k]} — ${RESULT_DETAIL[$k]}"
done
log "optional unopened (:${UNOPENED_PORT}): $OPTIONAL_UNOPENED — $OPTIONAL_DETAIL"
log "OVERALL: $OVERALL_S"
log "summary: $SUMMARY_PATH"

rm -rf "$TMPDIR_ACCEPT"
exit "$OVERALL"
